M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Mon 26 Aug 2024 01:36:19 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-26T13:36:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1122
%
G90
G05
T1
X1.575Y-4.55
X5.075Y-4.55
M30
