[package]
name = "bs02"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
cfgrammar = "0.13.8"
codespan-reporting = "0.11.1"
levenshtein = "1.0.5"
lrlex = "0.13.8"
lrpar = "0.13.8"

[build-dependencies]
cfgrammar = "0.13.8"
lrlex = "0.13.8"
lrpar = "0.13.8"
